CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email text NOT NULL,
	username text NOT NULL,
	"password" text NOT NULL,
	log_state bool NULL DEFAULT false,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


CREATE TABLE public.budgets (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int4 NULL,
	budget_title text NOT NULL,
	money_available int4 NOT NULL,
	date_created timestamp NULL,
	date_updated timestamp NULL,
	CONSTRAINT budgets_pkey PRIMARY KEY (id)
);

CREATE TABLE public.incomes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	budget_id int4 NOT NULL,
	income int4 NULL
)

CREATE TABLE public.purchases (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	budget_id int4 NULL,
	purchase_name text NOT NULL,
	purchase_cost int4 NOT NULL,
	CONSTRAINT purchases_pkey PRIMARY KEY (id)
);


CREATE TABLE public.supports (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int4 NULL,
	email text NOT NULL,
	subject text NOT NULL,
	"content" text NOT NULL,
	CONSTRAINT supports_pkey PRIMARY KEY (id)
);
